server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${APP_NAME:streamforge}

  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
      file-size-threshold: 2KB

aws:
  region: ${AWS_REGION:ap-southeast-1}
  dynamodb:
    environment: ${ENVIRONMENT:dev}
    prefix: ${DYNAMODB_PREFIX:streamforge}

azure:
  storage:
    account-name: ${AZURE_STORAGE_ACCOUNT_NAME:}
    container-name: ${AZURE_STORAGE_CONTAINER_NAME:vod-container}
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING:}
    public-url: ${AZURE_STORAGE_PUBLIC_URL:}

icurff:
  app:
    storage: ${ICURFF_APP_STORAGE:/app/storage}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      springframework:
        security: ${LOG_LEVEL_SECURITY:INFO}
